pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("flask-app")
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Remove old container if exists
                    bat "docker rm -f flask-app-container || exit 0"
                    
                    // Run new container
                    bat "docker run -d --name flask-app-container -p 5000:5000 flask-app"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    bat 'curl -f http://localhost:5000 || echo App not responding yet'
                }
            }
        }
    }
}
